[tool.poetry]
name = "vault-keyring-client"
version = "0.1.0"
description = ""
authors = ["Jakob Guldberg Aaes <jakob1379@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-or-later"

[tool.poetry.scripts]
vault-keyring-client = "vault_keyring_client.main:app"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
typer = "^0.12.3"
keyring = "^25.2.1"
ansible = "^9.6.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
